---
version: '3.8'
services:

  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp
    environment:
      - USERS=one|1234
      - ADDRESS=localhost
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
